### ISSUE TITLE
Error running pre-trained: coref_kernels.so: undefined symbol

### ISSUE THREAD

**Issue by amir-zeldes** [kentonl/e2e-coref#25]
I'm running into a problem running the pre-trained setup on Ubuntu, Python 2.7, TF==1.0.0:

```
e2e-coref$ python demo.py final
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    import coref_model as cm
  File "/home/ghost/e2e_coref/e2e-coref/coref_model.py", line 10, in <module>
    import coref_ops
  File "/home/ghost/e2e_coref/e2e-coref/coref_ops.py", line 4, in <module>
    coref_op_library = tf.load_op_library("./coref_kernels.so")
  File "/home/ghost/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

**Comment by mcjoshi** [comment]
I am getting the same error. @amir-zeldes did you found any solution to this ??

**Comment by ereday** [comment]
> I am getting the same error. @amir-zeldes did you found any solution to this ??
> 
> Got it fixed :)

@mcjoshi, if you still remember, could you explain how you fixed it ?
