### ISSUE TITLE
I follow your requirements ,and when running"python demo.py final", i get the erors , and i have run setup_all.sh file before running demo.py

### ISSUE THREAD

**Issue by smallsmallwood** [kentonl/e2e-coref#41]
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    import coref_model as cm
  File "/home/wlk/PycharmProjects/e2e/coref_model.py", line 10, in <module>
    import coref_ops
  File "/home/wlk/PycharmProjects/e2e/coref_ops.py", line 4, in <module>
    coref_op_library = tf.load_op_library("./coref_kernels.so")
  File "/home/wlk/anaconda3/envs/e2e/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

**Comment by mflis** [comment]
I had similar issue. In my case I've run `setup_all.sh` then `pip install -r requirements.txt`, that installed different version of `tensorflow-gpu`.

Solution: I've run `setup_all.sh` again (which creates `coref_kernels.so`). Now setup and demo had the same version of `tensorflow-gpu`, and linking is correct.
