### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by vadimsheinin** [kentonl/e2e-coref#52]
I installed the code and tried it for some time. However, several days ago suddently it stopped working. I am getting the following error:
Done loading word embeddings.
Traceback (most recent call last):
  File "demo.py", line 45, in <module>
    model = cm.CorefModel(config)
  File "/Users/vadims/anaphora/e2e-coref-master/coref_model.py", line 58, in __init__
    self.predictions, self.loss = self.get_predictions_and_loss(*self.input_tensors)
  File "/Users/vadims/anaphora/e2e-coref-master/coref_model.py", line 250, in get_predictions_and_loss
    elmo_module = hub.Module("https://tfhub.dev/google/elmo/2")
  File "/Users/vadims/anaconda/lib/python2.7/site-packages/tensorflow_hub/module.py", line 147, in __init__
    self._spec = as_module_spec(spec)
  File "/Users/vadims/anaconda/lib/python2.7/site-packages/tensorflow_hub/module.py", line 36, in as_module_spec
    return load_module_spec(spec)
  File "/Users/vadims/anaconda/lib/python2.7/site-packages/tensorflow_hub/module.py", line 61, in load_module_spec
    return registry.loader(path)
  File "/Users/vadims/anaconda/lib/python2.7/site-packages/tensorflow_hub/registry.py", line 45, in __call__
    self._name, args, kwargs))
RuntimeError: Missing implementation that supports: loader(*('/var/folders/2g/b2mxd7dn23j_myf6hm3yfbzc0000gn/T/tfhub_modules/9bb74bc86f9caffc8c47dd7b33ec4bb354d9602d',), **{})

Any ideas?
Thanks.

**Comment by kentonl** [comment]
I just tried it with
```
tensorflow>1.13.1
tensorflow-hub>0.4.0
```
and the demo still works for at least those versions. Are you still having trouble running the code?

**Comment by mjj1094** [comment]
@kentonl 
tensorflow-gpu       1.15.0
tensorflow-hub       0.8.0

the demo can not work for these version,can you show your precise version?

**Comment by mjj1094** [comment]
python demo.py  final
Traceback (most recent call last):
File "demo.py", line 45, in <module>
model = cm.CorefModel(config)
File "/data/private/mjj/project/coreference-resolution/e2e-coref/coref_model.py", line 58, in __init__
self.predictions, self.loss = self.get_predictions_and_loss(*self.input_tensors)
File "/data/private/mjj/project/coreference-resolution/e2e-coref/coref_model.py", line 250, in get_predictions_and_loss
elmo_module = hub.Module("https://tfhub.dev/google/elmo/2")
……
File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
