### ISSUE TITLE
NotFoundError when trying to run Singleton.py

### ISSUE THREAD

**Issue by sgoutam** [kentonl/e2e-coref#8]
Hi.

I am trying to implement your module for a project that I am currently working on. And there's an issue that I am facing when I try to set it up as per the instructions given.

The following traceback is generated when I run `python singleton.py best`
I am using Python 2.7 along with Tensorflow1.4.0 on a Ubuntu 16.04 LTS Base. I'm not really sure how to resolve this error, or where should I ideally look to resolve.

`Traceback (most recent call last):
  File "singleton.py", line 12, in <module>
    import coref_model as cm
  File "/home/sgoutam/e2e-coref/coref_model.py", line 10, in <module>
    import coref_ops
  File "/home/sgoutam/e2e-coref/coref_ops.py", line 4, in <module>
    coref_op_library = tf.load_op_library("./coref_kernels.so")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZTIN10tensorflow8OpKernelE`

**Comment by sgoutam** [comment]
Turns out it was a version error. Worked when I switched back to v1.0.0

**Comment by herbertchen1** [comment]
hi ，ive found its hard to get a tensorflow-gpu 1.0.0 ，did you know how to get it？？？
