### ISSUE TITLE
requirements.txt is broken

### ISSUE THREAD

**Issue by LifeIsStrange** [kentonl/e2e-coref#88]
ERROR: tensorflow-gpu 2.2.0 has requirement h5py<2.11.0,>=2.10.0, but you'll have h5py 2.8.0 which is incompatible.
ERROR: tensorboard 2.2.2 has requirement setuptools>=41.0.0, but you'll have setuptools 39.1.0 which is incompatible.
ERROR: google-auth 1.16.0 has requirement setuptools>=40.3.0, but you'll have setuptools 39.1.0 which is incompatible.

**Comment by LifeIsStrange** [comment]
no build error but crash on run

python demo.py final

Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    import coref_model as cm
  File "/home/stephane/coref2/3/e2e-coref/coref_model.py", line 17, in <module>
  
 import coref_ops
  File "/home/stephane/coref2/3/e2e-coref/coref_ops.py", line 8, in <module>
    coref_op_library = tf.load_op_library("./coref_kernels.so")
  File "/home/stephane/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: cannot open shared object file: No such file or directory


with 
tensorflow-gpu==1.14
tensorflow-hub==0.4.0
h5py
nltk
pyhocon
scipy
sklearn
setuptools==41.0.0

**Comment by LifeIsStrange** [comment]
todo try 1.12

**Comment by zlin888** [comment]
This setting works for me. I am using python 2.7

tensorflow==1.12.0
tensorflow-hub==0.2.0
pyhocon==0.3.50
nltk==3.0
sklearn
scipy
h5py
