### ISSUE TITLE
KeyError: 'bc/cctv/00/cctv_0000_1'

### ISSUE THREAD

**Issue by liyaoshigehaoren** [kentonl/e2e-coref#92]
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    if tf_global_step % eval_frequency == 0:
  File "/home/liyao/demo/e2e-coref-master/coref_model.py", line 560, in evaluate
    conll_results = conll.evaluate_conll(self.config["conll_eval_path"], coref_predictions, official_stdout)
  File "/home/liyao/demo/e2e-coref-master/conll.py", line 97, in evaluate_conll
    output_conll(gold_file, prediction_file, predictions)
  File "/home/liyao/demo/e2e-coref-master/conll.py", line 48, in output_conll
    start_map, end_map, word_map = prediction_map[doc_key]
KeyError: 'bc/cctv/00/cctv_0000_1'

**Comment by gaoya-J** [comment]
I have the simple problem,have you solve it???

**Comment by gaoya-J** [comment]
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    eval_summary, eval_f1 = model.evaluate(session)
  File "/home/tomtop5/e2e-coref-master/coref_model.py", line 563, in evaluate
    conll_results = conll.evaluate_conll(self.config["conll_eval_path"], coref_predictions, official_stdout)
  File "/home/tomtop5/e2e-coref-master/conll.py", line 97, in evaluate_conll
    output_conll(gold_file, prediction_file, predictions)
  File "/home/tomtop5/e2e-coref-master/conll.py", line 48, in output_conll
    start_map, end_map, word_map = prediction_map[doc_key]
KeyError: 'wb/eng/00/eng_0009_0'

**Comment by Zoeyyao27** [comment]
I have the same problem too!!!
